# Generated by Django 4.0.2 on 2022-02-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
