# Generated by Django 4.0.2 on 2022-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerya', '0002_fotos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/img/fotos'),
        ),
    ]
