# Generated by Django 4.0.2 on 2022-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerya', '0005_fotos_create_fotos_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='create',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
