# Generated by Django 4.0.2 on 2022-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerya', '0006_alter_fotos_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='fotos',
            name='seccion',
        ),
        migrations.AddField(
            model_name='fotos',
            name='seccion',
            field=models.ManyToManyField(to='Galerya.Secciones'),
        ),
    ]
