# Generated by Django 4.0.2 on 2022-02-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerya', '0008_remove_fotos_seccion_fotos_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='secciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='secciones'),
        ),
    ]
