# Generated by Django 4.0.2 on 2022-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerya', '0010_alter_secciones_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='imagen',
            field=models.ImageField(help_text='Las fotos deben ser 675x675 ', null=True, upload_to='secciones'),
        ),
    ]
