# Generated by Django 4.0.2 on 2022-02-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galerya', '0011_alter_secciones_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=1000)),
                ('imagen', models.ImageField(help_text='La foto de tu album', upload_to='album')),
            ],
        ),
    ]
