# Generated by Django 4.0.2 on 2022-02-10 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Galerya', '0013_fotos_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='seccion',
        ),
        migrations.AddField(
            model_name='album',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Galerya.secciones'),
        ),
    ]
