# Generated by Django 4.0.2 on 2022-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Mande una foto pequena', null=True, upload_to='blog'),
        ),
    ]
