# Generated by Django 4.0.2 on 2022-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(help_text='Con un limite de 3000 caracteres', max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(help_text='Con un limite de 50 caracteres', max_length=50),
        ),
    ]
